// File generated by FlutterFire CLI.
// This file is used to configure Firebase services for your app.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return const FirebaseOptions(
      apiKey: 'AIzaSyC2nrPhFNd2Z4B8IMKe40tSXzU3ewPcnu4',
      appId: '1:865440304449:android:d5a3c4d5143aef51b725c0',
      messagingSenderId: '865440304449',
      projectId: 'act14-3863b',
      storageBucket: 'act14-3863b.firebasestorage.app',
    );
  }
} 